// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// import HelloController from "./hello_controller"
// application.register("hello", HelloController)

import DashboardController from './dashboard_controller';
application.register('dashboard', DashboardController);

import DashboardTabController from './dashboard_tab_controller';
application.register('dashboardTab', DashboardTabController);

// import DashboardTabPanelController from './dashboard_tab_panel_controller';
// application.register('dashboardTabPanel', DashboardTabPanelController);

import CustomerWinsController from './customer_wins_controller';
application.register('customerWins', CustomerWinsController);

import ContributorsController from './contributors_controller';
application.register('contributors', ContributorsController);